/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.foladesoft.snippet_vs_title;

import java.awt.event.MouseEvent;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.FutureTask;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Vladislav
 */
public class Frame_Main extends javax.swing.JFrame {

    //private final String USER_AGENT = "Google Chrome/54.0.2840.99 m";
    /**
     * Creates new form Frame_Main
     */
    public Frame_Main() {
        initComponents();
    }

    private void expandAllNodes(JTree tree) {
        int j = tree.getRowCount();
        int i = 0;
        while (i < j) {
            tree.expandRow(i);
            i += 1;
            j = tree.getRowCount();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgr_SearchEngine = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        pnl_SearchEngine = new javax.swing.JPanel();
        rbtn_Yandex = new javax.swing.JRadioButton();
        rbtn_Google = new javax.swing.JRadioButton();
        btn_Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea_Keywords = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tree_Results = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 10, 0};
        jPanel2Layout.rowHeights = new int[] {0, 10, 0};
        jPanel2.setLayout(jPanel2Layout);

        pnl_SearchEngine.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search engine", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0};
        pnl_SearchEngine.setLayout(jPanel1Layout);

        bgr_SearchEngine.add(rbtn_Yandex);
        rbtn_Yandex.setText("Yandex");
        rbtn_Yandex.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 30);
        pnl_SearchEngine.add(rbtn_Yandex, gridBagConstraints);

        bgr_SearchEngine.add(rbtn_Google);
        rbtn_Google.setSelected(true);
        rbtn_Google.setText("Google");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 30);
        pnl_SearchEngine.add(rbtn_Google, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(pnl_SearchEngine, gridBagConstraints);

        btn_Search.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(btn_Search, gridBagConstraints);

        tarea_Keywords.setColumns(20);
        tarea_Keywords.setRows(5);
        tarea_Keywords.setText("купить наушники\nнаушники в Тюмени\nкрасные наушники купить");
        jScrollPane1.setViewportView(tarea_Keywords);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jSplitPane1.setTopComponent(jPanel2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree_Results.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_Results.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_ResultsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tree_Results);

        jSplitPane1.setRightComponent(jScrollPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jSplitPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testFuture() {
        
        try {
            FutureTask<Double> ft = new FutureTask<>(new Callable<Double>() {
                @Override
                public Double call() throws Exception {
                    System.out.println("Sleeping for 2 seconds");
                    Thread.sleep(2000);
                    return 0.5;
                }
            });
            System.out.println(ft.get());
            System.out.println(ft.get());
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed

        final DefaultMutableTreeNode root = new DefaultMutableTreeNode("Results");
        final DefaultTreeModel dtm = new DefaultTreeModel(root);

        final ExecutorService es = Executors.newCachedThreadPool();

        for (final String queryLine : tarea_Keywords.getText().split("\\n")) {
            if (!queryLine.trim().isEmpty()) {
                es.execute(new SearchTask(queryLine, root));
            }
        }

        try {
            es.shutdown();
            boolean finished;
            do {
                finished = es.awaitTermination(1000, TimeUnit.MILLISECONDS);
            } while (!finished);
            tree_Results.setModel(dtm);
            expandAllNodes(tree_Results);

        } catch (InterruptedException ex) {
            Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void tree_ResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_ResultsMouseClicked
		if (evt.getClickCount() > 1 && evt.getButton() == MouseEvent.BUTTON3) {
			expandAllNodes(tree_Results);
		}
    }//GEN-LAST:event_tree_ResultsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgr_SearchEngine;
    private javax.swing.JButton btn_Search;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnl_SearchEngine;
    private javax.swing.JRadioButton rbtn_Google;
    private javax.swing.JRadioButton rbtn_Yandex;
    private javax.swing.JTextArea tarea_Keywords;
    private javax.swing.JTree tree_Results;
    // End of variables declaration//GEN-END:variables
}
